import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./store";
import { ReduxProvider } from "./provider/ReduxProvider";

// import ReduxProvider from "./provider/reduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
